### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by sohail579** [rb-dock8s/serviio#25]
Hi Please can you update this to the latest version as its now patched for the Log4j Vulnerability

**Comment by soerentsch** [comment]
Hi, i had the same issue with the missing update. For my personal use i created an updated fork with Serviio 2.2.1 and FFmpeg 5.0.
Feel free to use it.
You can find the Docker file [here](https://github.com/soerentsch/docker-serviio)
And the Docker image at Docker Hub [here](https://hub.docker.com/u/soerentsch/serviio)

**Comment by killeriq** [comment]
former developer abandoned this project ? :(

As is connected to unRAID server, need to change whole docker

**Comment by soerentsch** [comment]
The migration at unRAID from this Docker image to my new Docker image is simple:
1. stop the old Docker image
2. install my new Docker image (via Apps Tab.)
3. mapp the same paths (lib and media) from the old Docker to the new Docker
4. start the new Docker

That's all folks ;-)

5. (optional) remove the old Docker image

**Comment by killeriq** [comment]
so i added yours, copy/pasted values / path / port from Former Serviio docker

Seems its working now ;) Thanks!

BTW : how hard is it to make it available in unRaid apps with prefilled values? = easier for everyone

**Comment by soerentsch** [comment]
I need to read the publishing guidelines (code signing, registering etc.) for unRaid apps.
Perhaps i find some time til the end of the month ;-)

**Comment by killeriq** [comment]
sure , i did install it already and works...

But this way your docker gets more popular...;)

**Comment by sohail579** [comment]
> The migration at unRAID from this Docker image to my new Docker image is simple:
> 
> 1. stop the old Docker image
> 2. install my new Docker image (via Apps Tab.)
> 3. mapp the same paths (lib and media) from the old Docker to the new Docker
> 4. start the new Docker
> 
> That's all folks ;-)
> 
> 5. (optional) remove the old Docker image

Thanks.  as its just a fork I edited the existing template I had and just changed the Repository really simple

**Comment by soerentsch** [comment]
> so i added yours, copy/pasted values / path / port from Former Serviio docker
> 
> Seems its working now ;) Thanks!
> 
> BTW : how hard is it to make it available in unRaid apps with prefilled values? = easier for everyone

You can now find my Version at Unraid Community Apps as "gucky79 Serviio"

**Comment by killeriq** [comment]
Thanks! 
BTW can you somehow update JAVA in the docker?

As older version was fine, but newer from some reason is not "promoting" on the network. Devices are not able to see it.
https://forum.serviio.org/viewtopic.php?t=23783

But i forgot how i got new version inside the docker :(

Thanks!

**Comment by soerentsch** [comment]
Java 8 is a dependency from the Serviio Server (see the [Minimal requirements](https://www.serviio.org/index.php?option=com_content&view=article&id=6&Itemid=4#minimal_requirements) )

But feel free to test a newer Java Version. At the Unraid Docker Tab, you can click on the Serviio Container Icon and then on "Console". By this way you have access in to the running alpine Linux.

The current Java Version is:
```
/ # java -version
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (IcedTea 3.20.0) (Alpine 8.302.08-r2)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)
```

**Comment by killeriq** [comment]
Thanks , but how to install newer version inside docker?

Found this is suggested : Recommended Version 8 Update 321, Release date: January 18, 2022

**Comment by soerentsch** [comment]
I think the easiest way is to add the alpine "edge" branch.
The newest Java Version at alpine edge is Update 312 -> [https://pkgs.alpinelinux.org/packages?name=openjdk8-jre&branch=edge](https://pkgs.alpinelinux.org/packages?name=openjdk8-jre&branch=edge)

**Comment by soerentsch** [comment]
To switch to alpine edge branch:

1. edit /etc/apk/repositories and replace v3.15 with edge
2. run apk update && apk upgrade

**Comment by killeriq** [comment]
trying to find how to edit, as there is no "nano" or "vim" :(

**Comment by soerentsch** [comment]
`apk add nano`
;-)
I will add the alpine "edge" brache with the next Docker Image Update

**Comment by killeriq** [comment]
getting there :D sry Windows user...
so replace those URLS:


https://dl-cdn.alpinelinux.org/alpine/v3.15/main
https://dl-cdn.alpinelinux.org/alpine/v3.15/community
http://dl-cdn.alpinelinux.org/alpine/v3.15/community
http://dl-cdn.alpinelinux.org/alpine/v3.15/main


---with this?

https://pkgs.alpinelinux.org/package/edge/community/x86/openjdk8-jre

---
nope...just the text "v3.15" with "edge" , done :D , updating

**Comment by killeriq** [comment]
i was able to upgrade it, but from some reason is still not promoting :(

So not really usable for me at the moment, no clue where is the issue...
I try on unraid board.

Thanks for fast action / help ! ;)

**Comment by soerentsch** [comment]
What is still not promoting? If you talk about DLNA promoting, then it's not an JAVA issue

**Comment by killeriq** [comment]
hmm there was similar issue in older version and Java fixed it back then, so no clue where is the issue now :(
no DLNA promoting = currently unusable

**Comment by soerentsch** [comment]
Hi @killeriq have you check that you use UDP for Port 1900. DLNA use UDP and not TCP

**Comment by ssersh** [comment]
> Hi, i had the same issue with the missing update. For my personal use i created an updated fork with Serviio 2.2.1 and FFmpeg 5.0. Feel free to use it. You can find the Docker file [here](https://github.com/soerentsch/docker-serviio) And the Docker image at Docker Hub [here](https://hub.docker.com/u/soerentsch/serviio)
@soerentsch, if you mount path /opt/serviio/config to unraid, serviio start or no ? For me serviio don't start. This is the autor mistake?
`09:40:59.566 [main] ERROR org.serviio.MediaServer - An unexpected error occurred. Ending the application. Message: org.serviio.profile.ProfilesDefinitionException: Profiles definition is not present.
java.lang.RuntimeException: org.serviio.profile.ProfilesDefinitionException: Profiles definition is not present.
        at org.serviio.profile.ProfileManager.parseProfilesFromFile(ProfileManager.java:186) ~[serviio.jar:?]
        at org.serviio.profile.ProfileManager.loadProfiles(ProfileManager.java:158) ~[serviio.jar:?]
        at org.serviio.MediaServer.main(MediaServer.java:137) ~[serviio.jar:?]
Caused by: org.serviio.profile.ProfilesDefinitionException: Profiles definition is not present.
        at org.serviio.profile.ProfilesDefinitionParser.parseDefinition(ProfilesDefinitionParser.java:148) ~[serviio.jar:?]
        at org.serviio.profile.ProfileManager.parseProfilesFromFile(ProfileManager.java:184) ~[serviio.jar:?]
        ... 2 more
An unexpected error occurred. Ending the application. Message: org.serviio.profile.ProfilesDefinitionException: Profiles definition is not present.. Check serviio.log for more details.`

**Comment by soerentsch** [comment]
Hi @ssersh ,
sounds like that the target path (on the host) is empty (error message "Profiles definition is not present.").
You can fix this by inital copy the missing files from the docker container to your host target path.
Here you find some infos to the `docker cp` command: [https://docs.docker.com/engine/reference/commandline/cp/](url)

**Comment by ssersh** [comment]
@soerentsch, thank you so much, it works! :)
